### ISSUE TITLE
Need Help with New Character and Server Setup

### ISSUE THREAD

**Issue by mod256118** [insthync/suriyun-unet-mmorpg#1]
Hi, I just got this kit for a week.
Can you show how to add new character and server setup for test?

**Comment by insthync** [comment]
Okay, I'll write guide about it now :p

**Comment by insthync** [comment]
For now, I can tell you the simple steps
1.) Prepare your character meshes
2.) Understand about CharacterActor component https://github.com/insthync/suriyun-unet-mmorpg/wiki/Character-Actor
3.) Place character inside CharacterActor 
4.) Set animator on CharacterActor

**Comment by mod256118** [comment]
I have made the Actor prefab, but how to add it into character selection list to make it available to spawn in game scene?

**Comment by mod256118** [comment]
I have made the CharacterActor, but how to add it into character selection?

**Comment by insthync** [comment]
Put the character mesh inside Game Object which attached CharacterActor as its child.

For example
You have Game Object which attached CharacterActor 
- Character Actor gameobject (Attach CharacterActor)
--- Character Mesh

**Comment by mod256118** [comment]
![123](https://cloud.githubusercontent.com/assets/23587503/20644836/4b617c72-b3fa-11e6-92ba-d20850d32577.jpg)

Can you check am I did some wrong there?
The new character is not showing in game.
The model is the warrior from SD_PACK#3

**Comment by insthync** [comment]
It's does not show in character list while creating new character right?

If yes, you have to create new CharacterData following the instruction: https://github.com/insthync/suriyun-unet-mmorpg/wiki/Character-Data then set its **Actor** as your **Character Actor** And set **Can Player Create** (The variable before an npc/monster variables) to true

Then Put the character into GameNetworkManager -> Config which usually placed in Home scene or place it in the resource folder.

**Comment by mod256118** [comment]
It works now. Thank you!
